#include "xparameters.h"

#define TRNGTESTBED_PLL_BASE_ADDR XPAR_TRNGTESTBED_0_BASEADDR

#define TRNGTESTBED_FIFO_BASE_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x200

#define TRNGTESTBED_STATUS_BASE_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x204

#define TRNGTESTBED_STATUS_MODE_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x204
#define TRNGTESTBED_STATUS_TOTAL_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x208
#define TRNGTESTBED_STATUS_COUNT_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x20C
#define TRNGTESTBED_STATUS_RNG_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x210
#define TRNGTESTBED_STATUS_MEMADDR_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x214
#define TRNGTESTBED_STATUS_HEALTH_ADDR XPAR_TRNGTESTBED_0_BASEADDR + 0x218

