route_design -nets [get_nets system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[0].gMeshCoupledXor.eMeshCoupledXor/*]
route_design -nets [get_nets system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[1].gOpenLoopMetaTrng.eOpenLoopMeta/eCascade/*]
route_design -nets [get_nets system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[1].gOpenLoopMetaTrng.eOpenLoopMeta/c_init]
route_design -nets [get_nets system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[1].gOpenLoopMetaTrng.eOpenLoopMeta/d_init]
route_design -nets [get_nets -of_objects [get_cells system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[2].gLwxnorLutTrng.eLwxnorLutTrng/gLwxnorLuts[*].e*]]
route_design -nets [get_nets system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[3].gXorRingTrng.eXorRingTrng/xor_net[*]]
route_design -nets [get_nets system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[4].gDnoTrng.eDnoTrng/eDno/*]
route_design -nets [get_nets system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[4].gDnoTrng.eDnoTrng/ro[*]]
route_design -nets [get_nets -of_objects [get_cells system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[5].gHybridFfsrTrng.eHybridFfsrTrng/e*]]
route_design -nets [get_nets -of_objects [get_cells system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[6].gLwxnorTrng.eLwxnorTrng/gLwxnors[*].e*]]
route_design -nets [get_nets -of_objects [get_cells system_i/TrngTestbed_0/inst/eCore/eSandbox/eTrngs/gEntropySourceInstantiation[7].gRoLdceTrng.eRoLdceTrng/gRoLdces[*].e*]]
